spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lifeonline_db_release?characterEncoding=UTF-8&serverTimezone=GMT-8
    username: root
    password: 960918
    type: com.alibaba.druid.pool.DruidDataSource